"""add risk fields and traceability

Revision ID: de9fa932de34
Revises: 
Create Date: 2026-06-09 15:20:10.325116+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'de9fa932de34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('risk_level', sa.String(length=16), nullable=True))
    op.add_column('sessions', sa.Column('risk_json', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('sessions', sa.Column('traceability_map', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'traceability_map')
    op.drop_column('sessions', 'risk_json')
    op.drop_column('sessions', 'risk_level')
    op.drop_column('sessions', 'risk_score')
    # ### end Alembic commands ###
